version: 0.2
phases:
  pre_build:
    commands:
      - php --version
  # build:
  #   commands:
  #     - phpunit --filter test_user_can_view_a_login_form
# artifacts:
#   files:
#     - '**-*'
#   discard-paths: no


