branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  Testapp-env:
    branch: null
    repository: null
global:
  application_name: TestApp
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/PHP 7.2 running
    on 64bit Amazon Linux/2.8.5
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
